FROM nvidia/cuda:12.4.1-cudnn-runtime-ubuntu22.04

WORKDIR /app

RUN apt-get update && apt-get install -y \
    python3 \
    python3-pip \
    && rm -rf /var/lib/apt/lists/*

RUN pip3 install --no-cache-dir \
    torch>=2.6.0 --index-url https://download.pytorch.org/whl/cu124 && \
    pip3 install --no-cache-dir "P_KNN[gpu]"

CMD ["P_KNN", "--help"]
